package:
  name: "bimlpa"
  version: "0.1.3"

source:
  git_rev: v0.1.3
  git_url: https://github.com/GiulioRossetti/BiMLPA

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python>=3.7
    - networkx>=2.4
    - numpy
    - scikit-learn
    - matplotlib

about:
  home: https://github.com/GiulioRossetti/BiMLPA
  license: BSD-2-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Community detection in bipartite networks using multi-label propagation algorithm"

extra:
  recipe-maintainers:
    - GiulioRossetti
